//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.EntityPathloss
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathlossByShift
    {
        public int Id { get; set; }
        public string Dotname { get; set; }
        public string Station { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> DateTest { get; set; }
        public Nullable<int> Shift { get; set; }
        public string Status { get; set; }
    }
}
