// <auto-generated />
namespace Report.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1992020_edit_tbl_action_ByErrorCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1992020_edit_tbl_action_ByErrorCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202009190231411_19.9.2020_edit_tbl_action_ByErrorCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
