// <auto-generated />
namespace Report.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20200917_edit_table_ActionErrorCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200917_edit_table_ActionErrorCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202009170956260_2020.09.17_edit_table_ActionErrorCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
