// <auto-generated />
namespace Report.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2020_09_17_1430_InitDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2020_09_17_1430_InitDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202009170731048_2020_09_17_14.30_InitDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
