//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.EntityAcount
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionErrorCode
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string ModelName { get; set; }
        public string Station { get; set; }
        public string ErrorCode { get; set; }
        public string PCname { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public string RootCause { get; set; }
        public int WorkSection { get; set; }
        public int Week { get; set; }
        public Nullable<System.DateTime> Begin { get; set; }
        public string Type { get; set; }
        public string ProblemDes { get; set; }
        public string report { get; set; }
    }
}
